[package]
name = "bvh_anim"
version = "0.2.1"
authors = ["George Burton <burtonageo@gmail.com>"]
repository = "https://github.com/burtonageo/bvh_anim"
documentation = "https://docs.rs/bvh_anim/"
readme = "Readme.md"
edition = "2018"
description = "A .bvh file parser"
keywords = ["bvh", "biovision", "parser", "animation", "skeletal"]
categories = ["rendering::data-formats"]
license = "MIT"
build = "build.rs"

[dependencies]
bstr = "0.1.2"
lexical = "2.1"
mint = "0.5"
num-traits = "0.2"
smallvec = "0.6"

[dependencies.libc]
version = "0.2"
optional = true

[build-dependencies.cbindgen]
version = "0.8"
optional = true

[dev-dependencies]
pretty_assertions = "0.6.1"
winit = "0.18"
wgpu = "0.2"

[features]
ffi = ["libc"]
bindings = ["cbindgen", "ffi"]
